# Generated by Django 5.0.4 on 2024-05-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('matricule', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'agent',
                'managed': False,
            },
        ),
    ]
