# Generated by Django 5.0.4 on 2024-05-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('codeuni', models.CharField(db_column='CODEUNI', max_length=3, primary_key=True, serialize=False)),
                ('desuni', models.CharField(blank=True, db_column='DESUNI', max_length=30, null=True)),
                ('type_uni', models.CharField(blank=True, db_column='TYPE_UNI', max_length=1, null=True)),
                ('adruni', models.CharField(blank=True, db_column='ADRUNI', max_length=70, null=True)),
                ('nssuni', models.CharField(blank=True, db_column='NSSUNI', max_length=20, null=True)),
                ('tirg', models.FloatField(blank=True, db_column='TIRG', null=True)),
                ('codewil', models.CharField(blank=True, db_column='CODEWIL', max_length=3, null=True)),
                ('unite_cnas', models.CharField(blank=True, db_column='UNITE_CNAS', max_length=4, null=True)),
                ('codecnassa', models.CharField(blank=True, db_column='CODECNASSA', max_length=5, null=True)),
                ('code', models.CharField(blank=True, db_column='CODE', max_length=4, null=True)),
                ('adress_mail', models.CharField(blank=True, max_length=30, null=True)),
                ('libelle_dir', models.CharField(blank=True, max_length=70, null=True)),
                ('tel', models.CharField(blank=True, max_length=12, null=True)),
                ('fax', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'UNITE',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='agent',
            table='AGENT',
        ),
    ]
