# Generated by Django 5.0.4 on 2024-05-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_paie_paiehist_alter_utilisateur_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postew',
            fields=[
                ('codepos', models.CharField(db_column='CODEPOS', max_length=6, primary_key=True, serialize=False)),
                ('despos', models.CharField(blank=True, db_column='DESPOS', max_length=50, null=True)),
                ('cat', models.CharField(blank=True, db_column='CAT', max_length=2, null=True)),
                ('codef', models.CharField(blank=True, db_column='CODEF', max_length=1, null=True)),
                ('codesf', models.CharField(blank=True, db_column='CODESF', max_length=3, null=True)),
                ('codessf', models.CharField(blank=True, max_length=4, null=True)),
                ('code_interime', models.CharField(blank=True, max_length=2, null=True)),
                ('code_interim', models.CharField(blank=True, max_length=2, null=True)),
                ('rub_a10', models.BooleanField(blank=True, db_column='Rub_A10', null=True)),
                ('nbj_a16', models.BooleanField(blank=True, db_column='nbj_A16', null=True)),
                ('ca', models.BooleanField(blank=True, null=True)),
                ('supprime', models.BooleanField(blank=True, db_column='SUPPRIME', null=True)),
            ],
            options={
                'db_table': 'POSTEW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sitadmin',
            fields=[
                ('codesita', models.CharField(db_column='CODESITA', max_length=3, primary_key=True, serialize=False)),
                ('dessita', models.CharField(blank=True, db_column='DESSITA', max_length=40, null=True)),
                ('type', models.CharField(blank=True, db_column='TYPE', max_length=1, null=True)),
                ('paye', models.BooleanField(blank=True, db_column='PAYE', null=True)),
            ],
            options={
                'db_table': 'SITADMIN',
                'managed': False,
            },
        ),
    ]
