# Generated by Django 5.0.4 on 2024-05-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_postew_sitadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(blank=True, db_column='MOIS', max_length=2, null=True)),
                ('exercice', models.CharField(blank=True, db_column='EXERCICE', max_length=4, null=True)),
                ('matricule', models.CharField(blank=True, db_column='MATAG', max_length=5, null=True)),
                ('modepaie', models.CharField(blank=True, db_column='MODEPAIE', max_length=1, null=True)),
                ('numcompte', models.CharField(blank=True, db_column='NUMCOMPTE', max_length=25, null=True)),
                ('sitfam', models.CharField(blank=True, db_column='SITFAM', max_length=1, null=True)),
                ('nbenf', models.IntegerField(blank=True, db_column='NBENF', null=True)),
                ('statut', models.CharField(blank=True, db_column='STATUT', max_length=1, null=True)),
                ('sitadmin', models.CharField(blank=True, db_column='SITADMIN', max_length=3, null=True)),
                ('datesita', models.DateTimeField(blank=True, db_column='DATESITA', null=True)),
                ('codepwn', models.CharField(blank=True, db_column='CODEPWN', max_length=6, null=True)),
                ('code_prof', models.CharField(blank=True, db_column='CODE_PROF', max_length=2, null=True)),
                ('typecais', models.CharField(blank=True, db_column='TYPECAIS', max_length=2, null=True)),
                ('nbj', models.FloatField(blank=True, db_column='NBJ', null=True)),
                ('cat', models.CharField(blank=True, db_column='CAT', max_length=2, null=True)),
                ('sec', models.IntegerField(blank=True, db_column='SEC', null=True)),
                ('sb', models.DecimalField(blank=True, db_column='SB', decimal_places=2, max_digits=18, null=True)),
                ('saluniq', models.BooleanField(blank=True, db_column='SALUNIQ', null=True)),
                ('codemutag', models.BooleanField(blank=True, db_column='CODEMUTAG', null=True)),
                ('nummutag', models.CharField(blank=True, db_column='NUMMUTAG', max_length=8, null=True)),
                ('codecapdec', models.BooleanField(blank=True, db_column='CODECAPDEC', null=True)),
                ('compchir', models.BooleanField(blank=True, db_column='COMPCHIR', null=True)),
                ('transveh', models.CharField(blank=True, db_column='TRANSVEH', max_length=1, null=True)),
                ('type_c', models.CharField(blank=True, max_length=1, null=True)),
                ('profession', models.CharField(blank=True, db_column='PROFESSION', max_length=70, null=True)),
                ('codeunia', models.CharField(blank=True, db_column='CODEUNIA', max_length=4, null=True)),
                ('code_dir', models.CharField(blank=True, max_length=1, null=True)),
                ('abbat_irg', models.BooleanField(blank=True, db_column='ABBAT_IRG', null=True)),
                ('handic', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'HIST_AGENT',
                'managed': False,
            },
        ),
    ]
